from abc import ABC, abstractmethod
class DisplayInterface(ABC):
    @abstractmethod
    def init(self): ...
    @abstractmethod
    def show(self, image): ...
    @abstractmethod
    def sleep(self): ...
